trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.7'
  displayName: 'Use Python 3.9.7'

- script: |
    python -m venv antenv
    source antenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd app
    gunicorn --bind=0.0.0.0 --timeout 600 app:app
  displayName: 'Start the Flask app'
